package integration

import (
	"bufio"
	"bytes"
	"encoding/json"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/fanzy618/pop/internal/buildinfo"
	"github.com/fanzy618/pop/internal/config"
	"github.com/fanzy618/pop/internal/console"
	"github.com/fanzy618/pop/internal/proxy"
	"github.com/fanzy618/pop/internal/store"
	"github.com/fanzy618/pop/internal/telemetry"
)

func TestConsoleNoAuthRequired(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, _ := setupConsoleAndProxy(t)

	resp, err := http.Get(consoleURL + "/api/stats")
	if err != nil {
		t.Fatalf("GET stats: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status=%d, want=%d", resp.StatusCode, http.StatusOK)
	}
}

func TestConsoleIndexAndAssets(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	indexResp, err := client.Get(consoleURL + "/")
	if err != nil {
		t.Fatalf("GET index: %v", err)
	}
	defer indexResp.Body.Close()

	if indexResp.StatusCode != http.StatusOK {
		t.Fatalf("index status=%d, want=%d", indexResp.StatusCode, http.StatusOK)
	}
	if ct := indexResp.Header.Get("Content-Type"); !strings.Contains(ct, "text/html") {
		t.Fatalf("index content-type=%q, want contains text/html", ct)
	}

	assetResp, err := client.Get(consoleURL + "/assets/app.js")
	if err != nil {
		t.Fatalf("GET app.js: %v", err)
	}
	defer assetResp.Body.Close()

	if assetResp.StatusCode != http.StatusOK {
		t.Fatalf("asset status=%d, want=%d", assetResp.StatusCode, http.StatusOK)
	}
}

func TestConsoleVersion(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	resp, err := client.Get(consoleURL + "/api/version")
	if err != nil {
		t.Fatalf("GET version: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status=%d, want=%d", resp.StatusCode, http.StatusOK)
	}
	if cacheControl := resp.Header.Get("Cache-Control"); !strings.Contains(cacheControl, "no-store") {
		t.Fatalf("cache-control=%q, want contains no-store", cacheControl)
	}

	var payload map[string]any
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		t.Fatalf("decode version payload: %v", err)
	}
	v, ok := payload["version"].(string)
	if !ok {
		t.Fatalf("version type=%T, want string", payload["version"])
	}
	if v != buildinfo.Version {
		t.Fatalf("version=%q, want=%q", v, buildinfo.Version)
	}
}

func TestConsoleHeaderIncludesVersionElement(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	respRoot, err := client.Get(consoleURL + "/")
	if err != nil {
		t.Fatalf("GET /: %v", err)
	}
	defer respRoot.Body.Close()
	rootBody, err := io.ReadAll(respRoot.Body)
	if err != nil {
		t.Fatalf("read / body: %v", err)
	}
	if !strings.Contains(string(rootBody), `id="app-version"`) {
		t.Fatalf("root page does not include app-version element")
	}

	respRules, err := client.Get(consoleURL + "/rules")
	if err != nil {
		t.Fatalf("GET /rules: %v", err)
	}
	defer respRules.Body.Close()
	rulesBody, err := io.ReadAll(respRules.Body)
	if err != nil {
		t.Fatalf("read /rules body: %v", err)
	}
	if !strings.Contains(string(rulesBody), `id="app-version"`) {
		t.Fatalf("rules page does not include app-version element")
	}
}

func TestConsoleAssetsIncludeVersionFetch(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	resp, err := client.Get(consoleURL + "/assets/app.js")
	if err != nil {
		t.Fatalf("GET app.js: %v", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read app.js: %v", err)
	}
	s := string(body)
	if !strings.Contains(s, "/api/version") {
		t.Fatalf("app.js does not include /api/version fetch")
	}
	if !strings.Contains(s, "visibilitychange") && !strings.Contains(s, "pageshow") && !strings.Contains(s, "focus") {
		t.Fatalf("app.js does not include tab activation refetch hooks")
	}
}

func TestConsoleRulesCRUDAndReorder(t *testing.T) {
	t.Parallel()

	consoleURL, _, dbPath, client := setupConsoleAndProxy(t)

	rule1 := map[string]any{"enabled": true, "pattern": "alpha.test", "action": "DIRECT"}
	rule2 := map[string]any{"enabled": true, "pattern": "*ads*", "action": "BLOCK", "block_status": 410}

	postJSON(t, client, consoleURL+"/api/rules", rule1, http.StatusCreated)
	postJSON(t, client, consoleURL+"/api/rules", rule2, http.StatusCreated)

	resp, err := client.Get(consoleURL + "/api/rules")
	if err != nil {
		t.Fatalf("GET rules: %v", err)
	}
	defer resp.Body.Close()

	var rulesList []config.RuleConfig
	if err := json.NewDecoder(resp.Body).Decode(&rulesList); err != nil {
		t.Fatalf("decode rules: %v", err)
	}

	if len(rulesList) != 2 {
		t.Fatalf("rules length=%d, want 2", len(rulesList))
	}
	if rulesList[0].ID <= 0 || rulesList[1].ID <= 0 {
		t.Fatalf("rule id should be generated by db: %+v", rulesList)
	}
	if rulesList[0].Action == "BLOCK" && rulesList[0].BlockStatus != 404 {
		t.Fatalf("block status=%d, want=404", rulesList[0].BlockStatus)
	}
	if rulesList[1].Action == "BLOCK" && rulesList[1].BlockStatus != 404 {
		t.Fatalf("block status=%d, want=404", rulesList[1].BlockStatus)
	}

	postJSON(t, client, consoleURL+"/api/rules/reorder", map[string]any{"ids": []int64{rulesList[0].ID, rulesList[1].ID}}, http.StatusOK)

	db, err := store.OpenSQLite(dbPath)
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	defer db.Close()
	persistedRules, err := db.ListRules()
	if err != nil {
		t.Fatalf("list persisted rules: %v", err)
	}
	if len(persistedRules) != 2 {
		t.Fatalf("persisted rules length=%d, want 2", len(persistedRules))
	}
}

func TestConsoleUpstreamsNameOptional(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	postJSON(t, client, consoleURL+"/api/upstreams", map[string]any{"url": "http://127.0.0.1:18080", "enabled": true}, http.StatusCreated)
	postJSON(t, client, consoleURL+"/api/upstreams", map[string]any{"name": "A", "url": "http://127.0.0.1:18081", "enabled": true}, http.StatusCreated)

	resp, err := client.Get(consoleURL + "/api/upstreams")
	if err != nil {
		t.Fatalf("GET upstreams: %v", err)
	}
	defer resp.Body.Close()

	var upstreams []config.UpstreamConfig
	if err := json.NewDecoder(resp.Body).Decode(&upstreams); err != nil {
		t.Fatalf("decode upstreams: %v", err)
	}
	if len(upstreams) != 2 {
		t.Fatalf("upstreams length=%d, want=2", len(upstreams))
	}
	if upstreams[0].ID <= 0 || upstreams[1].ID <= 0 {
		t.Fatalf("upstream id should be generated by db: %+v", upstreams)
	}
}

func TestConsoleStatsActivitiesAndSSE(t *testing.T) {
	t.Parallel()

	consoleURL, proxyURL, _, client := setupConsoleAndProxy(t)

	target := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte("ok"))
	}))
	t.Cleanup(target.Close)

	proxyParsed, err := url.Parse(proxyURL)
	if err != nil {
		t.Fatalf("parse proxy url: %v", err)
	}
	proxyClient := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyParsed)}}

	eventSeen := make(chan struct{}, 1)
	go func() {
		req, _ := http.NewRequest(http.MethodGet, consoleURL+"/api/activities/stream", nil)
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return
		}
		defer resp.Body.Close()
		br := bufio.NewReader(resp.Body)
		for {
			line, err := br.ReadString('\n')
			if err != nil {
				return
			}
			if strings.HasPrefix(line, "data: ") {
				select {
				case eventSeen <- struct{}{}:
				default:
				}
				return
			}
		}
	}()

	resp, err := proxyClient.Get(target.URL + "/telemetry")
	if err != nil {
		t.Fatalf("proxy request: %v", err)
	}
	_ = resp.Body.Close()

	select {
	case <-eventSeen:
	case <-time.After(3 * time.Second):
		t.Fatalf("did not receive SSE activity event")
	}

	statsResp, err := client.Get(consoleURL + "/api/stats")
	if err != nil {
		t.Fatalf("GET stats: %v", err)
	}
	defer statsResp.Body.Close()

	var stats map[string]any
	if err := json.NewDecoder(statsResp.Body).Decode(&stats); err != nil {
		t.Fatalf("decode stats: %v", err)
	}
	if stats["total_requests"].(float64) < 1 {
		t.Fatalf("expected total_requests >= 1, got %v", stats["total_requests"])
	}

	actsResp, err := client.Get(consoleURL + "/api/activities?limit=5")
	if err != nil {
		t.Fatalf("GET activities: %v", err)
	}
	defer actsResp.Body.Close()

	var events []map[string]any
	if err := json.NewDecoder(actsResp.Body).Decode(&events); err != nil {
		t.Fatalf("decode activities: %v", err)
	}
	if len(events) == 0 {
		t.Fatalf("expected at least one activity event")
	}
}

func TestConsoleRuleCreateWithUpstreamReference(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	postJSON(t, client, consoleURL+"/api/upstreams", map[string]any{"name": "proxy-a", "url": "http://127.0.0.1:18080", "enabled": true}, http.StatusCreated)

	upResp, err := client.Get(consoleURL + "/api/upstreams")
	if err != nil {
		t.Fatalf("GET upstreams: %v", err)
	}
	defer upResp.Body.Close()
	var upstreams []config.UpstreamConfig
	if err := json.NewDecoder(upResp.Body).Decode(&upstreams); err != nil {
		t.Fatalf("decode upstreams: %v", err)
	}
	if len(upstreams) == 0 {
		t.Fatalf("expected upstream list not empty")
	}

	postJSON(t, client, consoleURL+"/api/rules", map[string]any{
		"enabled":     true,
		"pattern":     "*.proxy-test.local",
		"action":      "PROXY",
		"upstream_id": upstreams[0].ID,
	}, http.StatusCreated)

	rulesResp, err := client.Get(consoleURL + "/api/rules")
	if err != nil {
		t.Fatalf("GET rules: %v", err)
	}
	defer rulesResp.Body.Close()
	var rulesList []config.RuleConfig
	if err := json.NewDecoder(rulesResp.Body).Decode(&rulesList); err != nil {
		t.Fatalf("decode rules: %v", err)
	}
	if len(rulesList) == 0 {
		t.Fatalf("expected rules not empty")
	}
	if rulesList[0].Action != "PROXY" {
		t.Fatalf("rule action=%s, want=PROXY", rulesList[0].Action)
	}
	if rulesList[0].UpstreamID != upstreams[0].ID {
		t.Fatalf("rule upstream_id=%d, want=%d", rulesList[0].UpstreamID, upstreams[0].ID)
	}
}

func TestConsoleDataBackupAndRestore(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	postJSON(t, client, consoleURL+"/api/upstreams", map[string]any{"name": "bk-up", "url": "http://127.0.0.1:18080", "enabled": true}, http.StatusCreated)

	upResp, err := client.Get(consoleURL + "/api/upstreams")
	if err != nil {
		t.Fatalf("GET upstreams: %v", err)
	}
	defer upResp.Body.Close()
	var upstreams []config.UpstreamConfig
	if err := json.NewDecoder(upResp.Body).Decode(&upstreams); err != nil {
		t.Fatalf("decode upstreams: %v", err)
	}
	if len(upstreams) != 1 {
		t.Fatalf("upstreams length=%d, want=1", len(upstreams))
	}

	postJSON(t, client, consoleURL+"/api/rules", map[string]any{
		"enabled":     true,
		"pattern":     "*.restore.local",
		"action":      "PROXY",
		"upstream_id": upstreams[0].ID,
	}, http.StatusCreated)

	bkResp, err := client.Get(consoleURL + "/api/data/backup")
	if err != nil {
		t.Fatalf("GET backup: %v", err)
	}
	defer bkResp.Body.Close()
	if bkResp.StatusCode != http.StatusOK {
		t.Fatalf("backup status=%d, want=%d", bkResp.StatusCode, http.StatusOK)
	}
	var backup map[string]any
	if err := json.NewDecoder(bkResp.Body).Decode(&backup); err != nil {
		t.Fatalf("decode backup: %v", err)
	}
	if backup["data_format_version"] == "" {
		t.Fatalf("backup data_format_version should not be empty")
	}

	postJSON(t, client, consoleURL+"/api/rules", map[string]any{"enabled": true, "pattern": "temp.local", "action": "DIRECT"}, http.StatusCreated)

	body, err := json.Marshal(backup)
	if err != nil {
		t.Fatalf("marshal backup payload: %v", err)
	}
	req, err := http.NewRequest(http.MethodPost, consoleURL+"/api/data/restore", strings.NewReader(string(body)))
	if err != nil {
		t.Fatalf("new restore request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	res, err := client.Do(req)
	if err != nil {
		t.Fatalf("POST restore: %v", err)
	}
	defer res.Body.Close()
	if res.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(res.Body)
		t.Fatalf("restore status=%d want=%d body=%s", res.StatusCode, http.StatusOK, strings.TrimSpace(string(raw)))
	}

	rulesResp, err := client.Get(consoleURL + "/api/rules")
	if err != nil {
		t.Fatalf("GET rules: %v", err)
	}
	defer rulesResp.Body.Close()
	var rulesList []config.RuleConfig
	if err := json.NewDecoder(rulesResp.Body).Decode(&rulesList); err != nil {
		t.Fatalf("decode rules: %v", err)
	}
	if len(rulesList) != 1 {
		t.Fatalf("rules length=%d, want=1", len(rulesList))
	}
	if rulesList[0].Pattern != "*.restore.local" {
		t.Fatalf("restored rule pattern=%s", rulesList[0].Pattern)
	}
}

func TestConsoleDataPageServed(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)
	resp, err := client.Get(consoleURL + "/data")
	if err != nil {
		t.Fatalf("GET data page: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status=%d want=%d", resp.StatusCode, http.StatusOK)
	}
}

func TestConsoleImportABP(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	postJSON(t, client, consoleURL+"/api/upstreams", map[string]any{"name": "abp-up", "url": "http://127.0.0.1:18080", "enabled": true}, http.StatusCreated)

	upResp, err := client.Get(consoleURL + "/api/upstreams")
	if err != nil {
		t.Fatalf("GET upstreams: %v", err)
	}
	defer upResp.Body.Close()
	var upstreams []config.UpstreamConfig
	if err := json.NewDecoder(upResp.Body).Decode(&upstreams); err != nil {
		t.Fatalf("decode upstreams: %v", err)
	}
	if len(upstreams) != 1 {
		t.Fatalf("upstreams length=%d, want=1", len(upstreams))
	}

	abpText := strings.Join([]string{
		"! comment",
		"||ads.example.com^",
		"@@||allow.example.com^",
		"example.org",
		"||sub.example.net^$third-party",
		"||ads.example.com^",
	}, "\n")

	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	part, err := writer.CreateFormFile("file", "rules.txt")
	if err != nil {
		t.Fatalf("create form file: %v", err)
	}
	if _, err := part.Write([]byte(abpText)); err != nil {
		t.Fatalf("write form file: %v", err)
	}
	_ = writer.WriteField("route_target", "UPSTREAM:"+strings.TrimSpace(strconv.FormatInt(upstreams[0].ID, 10)))
	_ = writer.WriteField("enabled", "true")
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	req, err := http.NewRequest(http.MethodPost, consoleURL+"/api/data/import-abp", &body)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("import abp: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(resp.Body)
		t.Fatalf("status=%d want=%d body=%s", resp.StatusCode, http.StatusOK, strings.TrimSpace(string(raw)))
	}

	rulesResp, err := client.Get(consoleURL + "/api/rules")
	if err != nil {
		t.Fatalf("GET rules: %v", err)
	}
	defer rulesResp.Body.Close()
	var rulesList []config.RuleConfig
	if err := json.NewDecoder(rulesResp.Body).Decode(&rulesList); err != nil {
		t.Fatalf("decode rules: %v", err)
	}
	if len(rulesList) != 6 {
		t.Fatalf("rules length=%d, want=6", len(rulesList))
	}
	contains := func(pattern string) bool {
		for _, r := range rulesList {
			if r.Pattern == pattern {
				return true
			}
		}
		return false
	}
	if !contains("ads.example.com") || !contains("*.ads.example.com") {
		t.Fatalf("expected ads.example.com patterns in imported rules")
	}
	if !contains("example.org") || !contains("*.example.org") {
		t.Fatalf("expected example.org patterns in imported rules")
	}
	if !contains("sub.example.net") || !contains("*.sub.example.net") {
		t.Fatalf("expected sub.example.net patterns in imported rules")
	}
	if contains("allow.example.com") || contains("*.allow.example.com") {
		t.Fatalf("exception rule should be skipped")
	}
}

func TestConsoleCreateRuleOverridesSamePattern(t *testing.T) {
	t.Parallel()

	consoleURL, _, _, client := setupConsoleAndProxy(t)

	postJSON(t, client, consoleURL+"/api/rules", map[string]any{"enabled": true, "pattern": "Example.com", "action": "DIRECT"}, http.StatusCreated)
	postJSON(t, client, consoleURL+"/api/rules", map[string]any{"enabled": true, "pattern": "example.com.", "action": "BLOCK", "block_status": 410}, http.StatusCreated)

	resp, err := client.Get(consoleURL + "/api/rules")
	if err != nil {
		t.Fatalf("GET rules: %v", err)
	}
	defer resp.Body.Close()

	var rulesList []config.RuleConfig
	if err := json.NewDecoder(resp.Body).Decode(&rulesList); err != nil {
		t.Fatalf("decode rules: %v", err)
	}
	if len(rulesList) != 1 {
		t.Fatalf("rules length=%d, want=1", len(rulesList))
	}
	if rulesList[0].Action != "BLOCK" {
		t.Fatalf("action=%s, want=BLOCK", rulesList[0].Action)
	}
	if rulesList[0].BlockStatus != 404 {
		t.Fatalf("block_status=%d, want=404", rulesList[0].BlockStatus)
	}
}

func setupConsoleAndProxy(t *testing.T) (consoleURL string, proxyURL string, dbPath string, client *http.Client) {
	t.Helper()

	dbPath = filepath.Join(t.TempDir(), "pop.sqlite")
	cfg := config.Default()
	cfg.SQLitePath = dbPath

	proxyServer := proxy.NewServer()
	telStore := telemetry.NewStore(1000, time.Minute)
	proxyServer.SetTelemetry(telStore)
	db, err := store.OpenSQLite(dbPath)
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	consoleServer, err := console.NewServer(cfg, db, proxyServer, telStore)
	if err != nil {
		t.Fatalf("new console server: %v", err)
	}

	consoleHTTP := httptest.NewServer(consoleServer)
	t.Cleanup(consoleHTTP.Close)

	proxyHTTP := httptest.NewServer(proxyServer)
	t.Cleanup(proxyHTTP.Close)

	return consoleHTTP.URL, proxyHTTP.URL, dbPath, http.DefaultClient
}

func postJSON(t *testing.T, client *http.Client, url string, payload any, wantStatus int) {
	t.Helper()

	body, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}

	req, err := http.NewRequest(http.MethodPost, url, strings.NewReader(string(body)))
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("post %s: %v", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != wantStatus {
		bodyRaw, _ := io.ReadAll(resp.Body)
		t.Fatalf("post %s status=%d want=%d body=%s", url, resp.StatusCode, wantStatus, strings.TrimSpace(string(bodyRaw)))
	}
}
